Jogo/Jogo-BackOffice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jogo_BackOffice.Filters;

namespace Jogo_BackOffice.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class HomeController : Controller
    {
        public ActionResult Index()
       { 
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Jogo/Jogo-BackOffice/Controllers/NivelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Jogo_BackOffice.Filters;
using Jogo_BackOffice.Models;
using Newtonsoft.Json;

namespace Jogo_BackOffice.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class NivelController : Controller
    {
        //
        // GET: /Nivel/

        public ActionResult Index()
        {

            using (var db = new NiveisContext())
            {
                ViewBag.Niveis = JsonConvert.SerializeObject(db.Niveis);  
                return View();
            }

        }

        [HttpPost]
        public JsonResult Cadastrar(NivelModel vm)
        {
            try
            {
                Nivel nivelRetorno;

                using (var db = new NiveisContext())
                {

                    if(db.Niveis.Any())
                    {
                        var id = db.Niveis.OrderByDescending(x => x.Id).First().Id;

                        var item = new Nivel(vm) { Id = id + 1 };

                        db.Niveis.Add(item);

                        db.SaveChanges();

                        nivelRetorno = item;

                    }
                    else
                    {
                        var item = new Nivel(vm);

                        db.Niveis.Add(item);

                        db.SaveChanges();

                        nivelRetorno = item;

                    }
                    

                }

                return Json(new { Sucesso = true, Mensagem = "Sucesso", Dados = JsonConvert.SerializeObject(nivelRetorno) });
            }
            catch (Exception ex)
            {
                return Json(new { Sucesso = false, Mensagem = "Erro" });
            }
         
        }

        [HttpPost]
        public JsonResult Editar(int id, NivelModel vm)
        {
            try
            {
                using (var db = new NiveisContext())
                {
                    var item = db.Niveis.FirstOrDefault(x => x.Id == id);

                    if (item != null)
                    {
                        item.AtualizarDominio(vm);

                        db.SaveChanges();
                    }
                    else
                    {
                        return Json(new { Sucesso = false });
                    }

                }

                return Json(new { Sucesso = true });
            }
            catch (Exception)
            {
                return Json(new { Sucesso = false });
            }

        }

        public JsonResult Excluir(int id)
        {

            try
            {
                using (var db = new NiveisContext())
                {
                    foreach (var item in db.Niveis.Where(item => item.Id == id))
                        db.Niveis.Remove(item);

                    db.SaveChanges();
                }

                return Json(new { Sucesso = true });
            }
            catch (Exception)
            {
                return Json(new { Sucesso = false });
            }

        }
    }
}

Jogo/Jogo-BackOffice/Controllers/SkinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jogo_BackOffice.Filters;
using Jogo_BackOffice.Models;
using Newtonsoft.Json;

namespace Jogo_BackOffice.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class SkinController : Controller
    {
      
        public ActionResult Index()
        {
            using (var db = new SkinsContext())
            {
                ViewBag.Skins = JsonConvert.SerializeObject(db.Skins);
                return View();
            }
        }

        [HttpPost]
        public JsonResult Cadastrar(SkinModel vm)
        {
            try
            {


                Skin skinRetorno;


                using (var db = new SkinsContext())
                

                    if (db.Skins.Any())
                    {
                        var id = db.Skins.OrderByDescending(x => x.Id).First().Id;

                        var item = new Skin(vm) { Id = id + 1 };

                        db.Skins.Add(item);

                        db.SaveChanges();

                        skinRetorno = item;

                    }
                    else
                    {
                        var item = new Skin(vm);

                        db.Skins.Add(item);

                        db.SaveChanges();

                        skinRetorno = item;

                    }

                return Json(new { Sucesso = true, Mensagem= "Sucesso", Dados = skinRetorno });
        
            }
            catch (Exception)
            {
                return Json(new { Sucesso = false, Mensagem = "Erro" });
            }
        }

       
        public JsonResult Excluir(int id)
        {

            using (var db = new SkinsContext())
            {
                var item = db.Skins.FirstOrDefault(x => x.Id == id);

                db.Skins.Remove(item);

                db.SaveChanges();
            }

            return Json(new { Sucesso = true });


        }

        [HttpPost]
        public JsonResult Editar(int id, SkinModel vm)
        {

            try
            {
                using (var db = new SkinsContext())
                {
                    var item = db.Skins.FirstOrDefault(x => x.Id == id);

                    if (item != null)
                    {
                        item.AtulizarDominio(vm);

                        db.SaveChanges();
                    }
                    else
                    {
                        return Json(new { Sucesso = false });
                    }

                }

                return Json(new { Sucesso = true });
            }
            catch (Exception)
            {
                return Json(new { Sucesso = false });
            }

        }


    }
}

Jogo/Jogo-BackOffice/Views/Home/Index.cshtml
<div class="container-fluid text-center content-middle">
    <div class="row content">
        <div class="col-sm-12 text-left">
            <h1>Bem vindo!</h1>
            <p>Aqui será feita a manutenção do jogo, cadastro de skins para os barcos, que serão comprados pelos jogadores e também os níveis de jogo podem ser cadastrados</p>
            <hr>
            <h3>Configurações</h3>

            <div class="row">

                @using (Html.BeginForm("Index", "Skin", FormMethod.Post, new { id = "SkinsForm" }))
                {
            
                    @Html.AntiForgeryToken()

                    <a href="javascript:document.getElementById('SkinsForm').submit()">
                        <div class="square square-xs-5 square-sm-4 square-md-3 square-lg-2 text-center float-left skins">
                            <div class="content-square">
                                <div class="table-square">
                                    <div class="table-cell-square">
                                        <span style="font-size: 25px;">SKINS</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
            
                }



                @using (Html.BeginForm("Index", "Nivel", FormMethod.Post, new { id = "NiveisForm" }))
                {
            
                    @Html.AntiForgeryToken()
            
                    <a href="javascript:document.getElementById('NiveisForm').submit()">
                        <div class="square square-xs-5 square-sm-4 square-md-3 square-lg-2 text-center float-left niveis">
                            <div class="content-square">
                                <div class="table-square">
                                    <div class="table-cell-square">
                                        <span style="font-size: 25px;">NÍVEIS</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
		       
                }


					
            </div>

        </div>
    </div>
</div>